# Please read before adding options
#
# horn-logic-bmc
# --------------
# This option is not added here because of https://github.com/seahorn/verify-c-common/issues/136
# It is explicitly added for yices in CI since yices needs to know logic.
#
verify_options:
# Optimization lelel. Lower to O1 for clearer counterexamples
  '-O1': ''
# 
# PREPROCESSING
#
  inline: ''
  enable-loop-idiom: ''
  enable-indvar: ''
  no-lower-gv-init-struct: ''
  externalize-addr-taken-functions: ''
  no-kill-vaarg: ''
  with-arith-overflow: true
  horn-unify-assumes: false
  bound: 20
# do not instrument library functions with memory assertions
  no-fat-fns: 'bcmp,memcpy,assert_bytes_match,ensure_linked_list_is_allocated,sea_aws_linked_list_is_valid'
  horn-gsa: false
# context-sensitive type-aware alias analysis 
  dsa: sea-cs-t
# weak support for function pointers. sea-dsa is better but less stable
  devirt-functions: 'types'
# bit-precise memory-precise operational semantics
  bmc: opsem
  horn-vcgen-use-ite: ''
# ignore control flow
  horn-vcgen-only-dataflow: false
# reduce by data dependence
  horn-bmc-coi: false
# static allocator supports symbolic allocation size
  sea-opsem-allocator: static
# stack allocation from a symbolic starting point
  horn-explicit-sp0: false
# lambdas for memory
  horn-bv2-lambdas: false
# use z3 simplifier during vcgen
  horn-bv2-simplify: true
# wide memory manager to track pointer sizes
  horn-bv2-extra-widemem: ''
# intermediate results in human readable form for debugging
  '-S': ''
# keep intermediate results for debugging 
  keep-temps: ''
  temp-dir: /tmp/cex
# time and result stats
  horn-stats: true
# produce counterexample harness
  cex: /tmp/h2.ll
# printable counterexample log
  log: cex
# number of words to unroll symbolic memcpy for array-based memory representation
# should be at least MAX_BUFFER_SIZE
  horn-array-sym-memcpy-unroll-count: 10
# print memory state as a table
# XXX still flaky, sometimes only the last byte can be trusted
  horn-bmc-hexdump: true
