verify_options:
# Optimization level
  '-O3': ''
# 
# PREPROCESSING
#
  inline: ''
  enable-loop-idiom: ''
  enable-indvar: ''
  no-lower-gv-init-struct: ''
  externalize-addr-taken-functions: ''
  no-kill-vaarg: ''
  with-arith-overflow: true
  horn-unify-assumes: true
  horn-gsa: ''
# do not instrument library functions with memory assertions 
  no-fat-fns: 'bcmp,memcpy,assert_bytes_match,ensure_linked_list_is_allocated,sea_aws_linked_list_is_valid'
# context-sensitive type-aware alias analysis 
  dsa: sea-cs-t
# weak support for function pointers. sea-dsa is better but less stable
  devirt-functions: 'types'
# bit-precise memory-precise operational semantics
  bmc: opsem
  horn-vcgen-use-ite: ''
# ignore control flow
  horn-vcgen-only-dataflow: true
# reduce by data dependence
  horn-bmc-coi: true
# static allocator supports symbolic allocation size
  sea-opsem-allocator: static
# stack allocation from a symbolic starting point
  horn-explicit-sp0: false
# lambdas for memory
  horn-bv2-lambdas: ''
# use z3 simplifier during vcgen
  horn-bv2-simplify: false
# wide memory manager to track pointer sizes
  horn-bv2-extra-widemem: ''
# intermediate results in human readable form for debugging
  '-S': ''
# keep intermediate results for debugging 
  keep-temps: ''
  temp-dir: /tmp/btor2mlir
# time and result stats
  horn-stats: true